---
services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_app
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - redis
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /owncloud-data:/mnt/data    # own—Åloud data volume, change as needed

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    ports:
      - 6371:6379
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/redis:/data
